# https://medium.com/@cmichel/how-to-deploy-a-create-react-app-with-github-actions-5e01f7a7b6b
name: Deployment

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Packages
        run: yarn install
      - name: Build page
        run: REACT_APP_VERSION=${GITHUB_REF##*/} REACT_APP_GIT_SHA=$GITHUB_SHA PUBLIC_URL=/qrbill yarn build
      - name: add 404
        run: cp build/index.html build/404.html
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
